### ISSUE TITLE
Add pattern matching for bangs

### ISSUE THREAD

**Issue by babastienne** [sophie-glk/bang#1]
If I want to use multiple bangs to redirect on the same URL I need to duplicate the URL so I was thinking about using a pattern matching in order to make it easier.

**Example**

For example if I want to use the bang !spotify to search a music and also want it to works when I use the bang !spoti, today I need this configuration :
![image](https://user-images.githubusercontent.com/16348048/63585551-ad54d280-c59f-11e9-8c30-5b4d84f36b71.png)

Maybe using a pattern like `"spoti"||"spotify" it could work and be like that : 

![image](https://user-images.githubusercontent.com/16348048/63585634-e12ff800-c59f-11e9-9252-5e7da3d31914.png)

**Comment by sophie-glk** [comment]
Thanks for the suggestion (and for using this addon)! I have now added alias support. Because spaces don't work in bang names anyway i have decided to just use a space as a separator. You should now be able to use multiple names for a bang like this:
"spoti spotify music" .
It would be nice if you could give me feedback / tell me if have introduced any bugs, before i push the update to the store.

**Comment by babastienne** [comment]
Thanks for adding this feature. I'm currently testing it, I will keep you informed if I find any issue.

**Comment by babastienne** [comment]
The multiple names for a bang is working just fine, thank you very much for adding this.
I haven't notice anything in particular related to this.

However I've noticed two minor issues on different topics. I will create them soon.

I let you close the issue if you think the problem is solved. In my opinion it is.
