### ISSUE TITLE
[Bug?] Bangs are case sensitive

### ISSUE THREAD

**Issue by TorMechia** [sophie-glk/bang#17]
I apologize in advance if this is an end-user issue (i.e. I'm a moron).
___
Bang shortcuts in lowercase work as intended...
![image](https://user-images.githubusercontent.com/56943516/115440823-2a55a680-a1de-11eb-9f4a-d966311af958.png)
![image](https://user-images.githubusercontent.com/56943516/115440865-39d4ef80-a1de-11eb-8723-4e71a1decddd.png)

But do a normal search when in uppercase.
![image](https://user-images.githubusercontent.com/56943516/115440934-49eccf00-a1de-11eb-83c6-0ec914ccfdb2.png)
![image](https://user-images.githubusercontent.com/56943516/115441015-60932600-a1de-11eb-824b-a30d7f8983e2.png)

Is this intended?

**Comment by babastienne** [comment]
This extension offers a a better implementation of the bangs than just the bang feature of DDG, because it allow the user to define himself its own bangs.
Therefore, considering that !BANG should be the same that !bang is quite touchy because a user could have define two differents bangs in his own configuration.

Still, I'm pretty sure it would be possible to implement something :
When a user search something with a bang that contains upppercase letters and that bang does not exists in the custom configuration of the user, then the bang is automatically converted in lowercase before running the search.

**Comment by sophie-glk** [comment]
This should be an easy one line fix

**Comment by sophie-glk** [comment]
In the latest development version this should be fixed
